import Head from "next/head";
import Finder from "../components/finder";
import { getFolderStructure } from "../data/fs";

export default function Home({ root }) {
  return (
    <div>
      <Head>
        <title>Folder Structure App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-800 text-white">
        <Finder root={root} />
      </div>
    </div>
  );
}
export function getServerSideProps() {
  const root = getFolderStructure("node_modules");
  return {
    props: {
      root,
    },
  };
}
