import Head from "next/head";
import { useState, useEffect } from "react";
import Finder from "../components/finder";
import { getFolders } from "../fetch/folders";

export default function Home({ root }) {
  const [data, setData] = useState(null);
  useEffect(() => {
    getFolders("node_modules").then(setData);
  }, [setData]);
  return (
    <div>
      <Head>
        <title>Folder Structure App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-800 text-white">
        {data == null || (
          <>
            {typeof data == "object" ? (
              <Finder root={data} />
            ) : (
              <div className="text-red-600">error:{data}</div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
