import Head from "next/head";
import { useState, useEffect } from "react";
import Finder from "../components/finder";
import { getFolders } from "../fetch/folders";

export default function Home({ path }) {
  return (
    <div>
      <Head>
        <title>Folder Structure App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-800 text-white">
        <Finder path={path} />
      </div>
    </div>
  );
}

export function getServerSideProps() {
  return {
    props: {
      path: process.env.BASE || "node_modules",
    },
  };
}
